### ISSUE TITLE
CPAN dependency URLs are broken

### ISSUE THREAD

**Issue by dndhm** [linode/homebrew-cli#21]
CPAN has updated its url pattern, so all CPAN-hosted dependencies in `linode-cli.rb` are broken.

The new pattern is `http://search.cpan.org/CPAN/authors/...`

**Comment by dndhm** [comment]
I have a working fix on a local branch if that's useful for anyone.

**Comment by jamesottinger** [comment]
@dndhm, thank you for reporting.  The link to Scalar-List-Utils was just updated, so that may have been broken for you.  I wasn't aware that the CPAN patterns were changing. They are working for me now. You are always welcome to contribute. We appreciate it.

**Comment by dndhm** [comment]
I guess I was just trying to install at a bad time! Seems fine now.

**Comment by marckohlbrugge** [comment]
Seems to still/again be broken.

```bash
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "linode-cli--Module::Metadata"
Download failed: http://www.cpan.org/authors/id/E/ET/ETHER/Module-Metadata-1.000027.tar.gz
```
