### ISSUE TITLE
Crypt-SSLeay build process hangs

### ISSUE THREAD

**Issue by vendion** [linode/homebrew-cli#4]
The Crypt-SSLeay module hangs on building.  The output only has the following

```
==> Downloading http://www.cpan.org/authors/id/N/NA/NANIS/Crypt-SSLeay-0.64.tar.gz
Already downloaded: /Library/Caches/Homebrew/linode-cli--Crypt::SSLeay-0.64.tar.gz
==> perl Makefile.PL INSTALL_BASE=/usr/local/Cellar/linode-cli/1.4.2/libexec -n
```

I gave it a day so fair an there has been no progress made on it.

Building on OSX 10.9.5 and Perl 5.20.1 (installed via perlbrew).

**Comment by jamesottinger** [comment]
Hello venion,
Perhaps your install got interrupted? You can re-install or update to a newer version and stomp it.
```
brew update
brew upgrade linode-cli
```

**Comment by vendion** [comment]
I'm not sure what the cause was exactly, but no matter what when I tried to upgrade linode-cli it would hang at the same place.  Updating homebrew's information with ```brew update``` didn't change anything.  After upgrading my mac to OSX 10.10 though I was able to update linode-cli without issue.

**Comment by jamesottinger** [comment]
Ok, I'll close the issue then.  Thanks!
